CREATE TABLE parked_cars (
`id` INT NOT NULPRIMARYPRIMARYL PRIMARY KEY AUTO_INCREMENT,
`parkinglot_id` INT NOT NULL,
`position` INT NOT NULL,
`license` CHAR(20) NOT NULL
) ENGINE = InnoDB DEFAULT CHARSET = utf8;

CREATE TABLE parkinglot_list (
`id` INT NOT NULPRIMARYPRIMARYL PRIMARY KEY AUTO_INCREMENT,
`name` CHAR(10) NULL,
`capacity` INT NOT NULL
) ENGINE = InnoDB DEFAULT CHARSET = utf8;